import React, { useState, useEffect } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Box,
} from '@mui/material';
import { ReusableTextField, ReusableSelect } from './FormComponents';
import { useFormValidation } from '../../hooks/useFormValidation';

export interface FormFieldConfig {
  name: string;
  label: string;
  type: 'text' | 'email' | 'password' | 'select' | 'checkbox' | 'date';
  required?: boolean;
  disabled?: boolean | ((editingItem: any) => boolean);
  options?: { value: string; label: string }[] | (() => { value: string; label: string }[]) | (() => Promise<{ value: string; label: string }[]>);
  validation?: 'name' | 'phone' | 'email' | ((value: any, formData?: any) => string | null);
  autoGenerate?: (formData: any, editingItem: any) => string;
  gridColumn?: string;
  helperText?: string | ((formData: any, editingItem: any) => string);
  placeholder?: string | ((formData: any, editingItem: any) => string);
  min?: string | ((formData: any, editingItem: any) => string | undefined);
  max?: string | ((formData: any, editingItem: any) => string | undefined);
}

interface DynamicFormProps {
  open: boolean;
  onClose: () => void;
  onSubmit: (data: any) => void;
  editingItem?: any;
  title: string;
  fields: FormFieldConfig[];
}

const DynamicForm: React.FC<DynamicFormProps> = ({
  open,
  onClose,
  onSubmit,
  editingItem,
  title,
  fields
}) => {
  const [formData, setFormData] = useState<{[key: string]: any}>({});
  const [initialData, setInitialData] = useState<{[key: string]: any}>({});
  const [errors, setErrors] = useState<{[key: string]: string}>({});
  const [autoGenerated, setAutoGenerated] = useState<{[key: string]: string}>({});
  const [selectOptions, setSelectOptions] = useState<{[key: string]: { value: string; label: string }[]}>({});

  const {
    nameValidation,
    phoneValidation,
    phoneFormatValidation,
    validatePhoneFormat,
    validateNameUniqueness,
    validatePhoneUniqueness,
    resetValidations
  } = useFormValidation();

  useEffect(() => {
    if (open) {
      setErrors({});
      resetValidations();
      
      const initialData: {[key: string]: any} = {};
      fields.forEach(field => {
        initialData[field.name] = editingItem?.[field.name] || '';
      });
      setFormData(initialData);
      setInitialData(initialData);
      
      // Generate auto-generated values
      const generated: {[key: string]: string} = {};
      fields.forEach(field => {
        if (field.autoGenerate && !editingItem) {
          generated[field.name] = field.autoGenerate(initialData, editingItem);
        }
      });
      setAutoGenerated(generated);
      
      // Load async options
      const loadOptions = async () => {
        const options: {[key: string]: { value: string; label: string }[]} = {};
        for (const field of fields) {
          if (field.type === 'select' && typeof field.options === 'function') {
            try {
              const result = field.options();
              options[field.name] = result instanceof Promise ? await result : result;
            } catch (error) {
              options[field.name] = [];
            }
          }
        }
        setSelectOptions(options);
      };
      
      loadOptions();
    }
  }, [open]);

  useEffect(() => {
    // Update auto-generated values when form data changes
    if (open) {
      const generated: {[key: string]: string} = {};
      fields.forEach(field => {
        if (field.autoGenerate && !editingItem) {
          generated[field.name] = field.autoGenerate(formData, editingItem);
        }
      });
      setAutoGenerated(generated);
    }
  }, [formData, editingItem, open]);

  useEffect(() => {
    // Handle validations
    if (open) {
      const nameField = fields.find(f => f.validation === 'name');
      const phoneField = fields.find(f => f.validation === 'phone');
      
      if (nameField && formData[nameField.name]) {
        const timer = setTimeout(() => {
          validateNameUniqueness(formData[nameField.name], formData.role, editingItem);
        }, 500);
        return () => clearTimeout(timer);
      }
      
      if (phoneField && formData[phoneField.name]) {
        validatePhoneFormat(formData[phoneField.name]);
        const timer = setTimeout(() => {
          validatePhoneUniqueness(formData[phoneField.name], formData.role, editingItem);
        }, 500);
        return () => clearTimeout(timer);
      }
    }
  }, [formData, editingItem, open, validateNameUniqueness, validatePhoneFormat, validatePhoneUniqueness]);

  // Check if form has changes
  const hasChanges = editingItem ? 
    Object.keys(formData).some(key => formData[key] !== initialData[key]) : 
    true;

  const handleFieldChange = (fieldName: string, value: any) => {
    setFormData({ ...formData, [fieldName]: value });
    if (errors[fieldName]) {
      setErrors({ ...errors, [fieldName]: '' });
    }
  };

  const getFieldError = (field: FormFieldConfig) => {
    if (field.validation === 'name') {
      return !!errors[field.name] || nameValidation.status === 'taken';
    }
    if (field.validation === 'phone') {
      return !!errors[field.name] || !phoneFormatValidation.isValid || phoneValidation.status === 'taken';
    }
    if (typeof field.validation === 'function') {
      const validationError = field.validation(formData[field.name], formData);
      return !!errors[field.name] || !!validationError;
    }
    return !!errors[field.name];
  };

  const getFieldHelperText = (field: FormFieldConfig) => {
    if (field.validation === 'name') {
      return errors[field.name] || nameValidation.message;
    }
    if (field.validation === 'phone') {
      return errors[field.name] || (!phoneFormatValidation.isValid ? phoneFormatValidation.message : phoneValidation.message);
    }
    
    // Handle custom validation
    if (typeof field.validation === 'function') {
      const validationError = field.validation(formData[field.name], formData);
      if (validationError) {
        return validationError;
      }
    }
    
    if (typeof field.helperText === 'function') {
      return field.helperText(formData, editingItem);
    }
    
    if (field.autoGenerate && !formData[field.name] && autoGenerated[field.name]) {
      return `Auto-generated: ${autoGenerated[field.name]}`;
    }
    
    return errors[field.name] || field.helperText || '';
  };

  const getFieldValidation = (field: FormFieldConfig) => {
    if (field.validation === 'name') return nameValidation;
    if (field.validation === 'phone') return phoneValidation;
    return undefined;
  };

  const handleSubmit = () => {
    const newErrors: {[key: string]: string} = {};
    
    fields.forEach(field => {
      if (field.required) {
        const value = formData[field.name] || autoGenerated[field.name];
        if (!value || (typeof value === 'string' && !value.trim())) {
          newErrors[field.name] = `${field.label} is required`;
        }
      }
      
      // Custom validation
      if (typeof field.validation === 'function') {
        const value = formData[field.name] || autoGenerated[field.name];
        const validationError = field.validation(value, formData);
        if (validationError) {
          newErrors[field.name] = validationError;
        }
      }
    });
    
    setErrors(newErrors);
    
    if (Object.keys(newErrors).length > 0) {
      return;
    }
    
    // Merge form data with auto-generated values
    const submissionData = { ...formData };
    Object.keys(autoGenerated).forEach(key => {
      if (!submissionData[key]) {
        submissionData[key] = autoGenerated[key];
      }
    });
    
    onSubmit(submissionData);
    // Don't auto-close - let parent handle closing after successful submission
  };

  const renderField = (field: FormFieldConfig) => {
    const value = formData[field.name] || autoGenerated[field.name] || '';
    const isDisabled = typeof field.disabled === 'function' ? field.disabled(editingItem) : field.disabled;
    
    if (field.type === 'select') {
      const options = selectOptions[field.name] || (Array.isArray(field.options) ? field.options : []);
      return (
        <ReusableSelect
          key={field.name}
          label={field.label}
          value={value}
          onChange={(val) => handleFieldChange(field.name, val)}
          options={options}
          required={field.required}
          error={getFieldError(field)}
          helperText={getFieldHelperText(field)}
          gridColumn={field.gridColumn}
        />
      );
    }
    
    if (field.type === 'checkbox') {
      return (
        <Box key={field.name} sx={{ gridColumn: field.gridColumn || '1 / -1', display: 'flex', alignItems: 'center', gap: 1 }}>
          <input
            type="checkbox"
            id={field.name}
            checked={!!formData[field.name]}
            onChange={(e) => handleFieldChange(field.name, e.target.checked)}
          />
          <label htmlFor={field.name}>{field.label}</label>
        </Box>
      );
    }
    
    return (
      <ReusableTextField
        key={field.name}
        label={field.label}
        value={value}
        onChange={(val) => handleFieldChange(field.name, val)}
        type={field.type}
        required={field.required}
        disabled={isDisabled}
        error={getFieldError(field)}
        helperText={getFieldHelperText(field)}
        placeholder={typeof field.placeholder === 'function' ? field.placeholder(formData, editingItem) : field.placeholder}
        validation={getFieldValidation(field)}
        gridColumn={field.gridColumn}
        min={typeof field.min === 'function' ? field.min(formData, editingItem) : field.min}
        max={typeof field.max === 'function' ? field.max(formData, editingItem) : field.max}
      />
    );
  };

  return (
    <Dialog 
      open={open} 
      onClose={onClose} 
      maxWidth="md" 
      fullWidth
      fullScreen={window.innerWidth < 600}
      sx={{
        '& .MuiDialog-paper': {
          margin: { xs: 0, sm: 2 },
          width: { xs: '100%', sm: '100%' },
          height: { xs: '100%', sm: 'auto' },
          maxHeight: { xs: '100%', sm: '90vh' },
          borderRadius: { xs: 0, sm: 2 },
          display: 'flex',
          flexDirection: 'column'
        },
        '& .MuiDialogContent-root': {
          flex: 1,
          overflow: 'auto',
          px: { xs: 2, sm: 3 },
          py: { xs: 1, sm: 2 }
        }
      }}
    >
      <DialogTitle sx={{ 
        borderBottom: '1px solid #e0e0e0',
        px: { xs: 2, sm: 3 },
        py: { xs: 1.5, sm: 2 }
      }}>
        {editingItem ? `Edit ${title}` : `Add New ${title}`}
      </DialogTitle>
      <DialogContent>
        <Box sx={{ 
          display: 'grid', 
          gridTemplateColumns: { xs: '1fr', sm: '1fr 1fr' }, 
          gap: { xs: 1.5, sm: 2 }, 
          mt: 1 
        }}>
          {fields.map(renderField)}
        </Box>
      </DialogContent>
      <DialogActions sx={{ 
        borderTop: '1px solid #e0e0e0', 
        pt: 2,
        px: { xs: 2, sm: 3 },
        pb: { xs: 2, sm: 2 },
        flexDirection: 'row',
        gap: { xs: 1, sm: 0 },
        position: { xs: 'sticky', sm: 'static' },
        bottom: { xs: 0, sm: 'auto' },
        bgcolor: 'background.paper',
        zIndex: 1
      }}>
        <Box sx={{ 
          display: 'flex', 
          gap: 1, 
          width: { xs: '100%', sm: 'auto' }
        }}>
          <Button 
            onClick={onClose}
            sx={{ flex: { xs: 1, sm: 'none' } }}
          >
            Cancel
          </Button>
          <Button 
            onClick={handleSubmit} 
            variant="contained"
            disabled={nameValidation.status === 'taken' || phoneValidation.status === 'taken' || !phoneFormatValidation.isValid || !hasChanges}
            sx={{ flex: { xs: 1, sm: 'none' } }}
          >
            {editingItem ? 'Update' : 'Create'} {title}
          </Button>
        </Box>
      </DialogActions>
    </Dialog>
  );
};

export default DynamicForm;
